title: Insights Operator Utils
description: Utility functions that are shared for insights-operator-* repositories 
baseurl: "/insights-operator-utils"
url: "https://redhatinsights.github.io"

heading_anchors: true
search_enabled: false

aux_links:
  "Github repository":
    - "https://github.com/RedHatInsights/insights-operator-utils"

footer_content: "Copyright &copy; 2020 Red Hat, Inc.</a>"

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
